# gitlab CI/CD pipeline配置文件
image: centos

stages:
    - test
    - rpm

before_script:
    - mkdir -p /go/src/gitlab.local.com/golang
    - ln -s `pwd` /go/src/gitlab.local.com/golang/go-healthcheck && cd /go/src/gitlab.local.com/golang/go-healthcheck

# test stage
# job 1 test go vet
job_govet:
    stage: test
    image: machiel/go-golint:1.11
    script:
        - bash ./scripts/ci-govet-check.sh
    tags:
        - dev
# job 2 test go fmt
job_gofmt:
    stage: test
    image: machiel/go-golint:1.11
    script:
        - bash ./scripts/ci-gofmt-check.sh
    tags:
        - dev
# job 3 test go lint
job_golint:
    stage: test
    image: machiel/go-golint:1.11
    script:
        - bash ./scripts/ci-golint-check.sh
    tags:
        - dev
# job 4 test go unit test
job_unit:
    stage: test
    image: machiel/go-golint:1.11
    script:
        - bash ./scripts/ci-gotest-check.sh
    tags:
        - dev

